# Configuration pour microservice-produit
# Ce fichier doit être sur GitHub dans votre repo config-repo

server:
  port: 8087

spring:
  datasource:
    url: jdbc:h2:mem:produitdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

# Configuration pour simuler le timeout (pour tester Hystrix)
produit:
  simulate-timeout: false  # Changer à true pour simuler un timeout
  timeout-delay: 5000      # Délai en millisecondes (5 secondes)

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
